version: '3'

services:
  flask-app:
    build: ./
    ports:
      - "5000:5000"
    volumes:
      - "./:/app"
    depends_on:
      - redis

  redis:
    image: redis
    ports:
      - "6379:6379"