version: '3'
services:
  api:
    container_name: flask-container
    build: .
    entrypoint: python app.py
    env_file:
      - .env
    ports:
      - '5000:5000'
    volumes:
      - .:/app # local_directory:WORKDIR
  redis:
    image: redis
    container_name: redis-container
    ports:
      - "6379:6379"